'use client';

import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Rss, ArrowRight, Loader2, Clock } from 'lucide-react';
import { useCollection, useFirestore, useMemoFirebase } from "../firebase";
import type { NewsArticle } from "../lib/types";
import { format } from 'date-fns';
import { Timestamp, collection } from 'firebase/firestore';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "../components/ui/accordion";
import { ScrollArea } from "../components/ui/scroll-area";
import { useMemo } from 'react';

interface AuctionNewsProps {
  latestOnly?: boolean;
}

export function AuctionNews({ latestOnly = false }: AuctionNewsProps) {
  const firestore = useFirestore();

  const newsQuery = useMemoFirebase(() => {
    if (!firestore) return null;
    return collection(firestore, 'newsArticles');
  }, [firestore]);

  const { data: articles, isLoading } = useCollection<NewsArticle>(newsQuery);

  const getSafeDate = (date: any): Date => {
    if (!date) return new Date(0);
    if (typeof date === 'string') return new Date(date);
    if (date instanceof Timestamp) return date.toDate();
    if (date.seconds && typeof date.seconds === 'number') return new Date(date.seconds * 1000);
    if (date.toDate && typeof date.toDate === 'function') return date.toDate();
    return new Date(0);
  };
  
  const sortedArticles = useMemo(() => {
    return (articles || []).sort((a, b) => {
      const dateA = getSafeDate(a.publishedAt);
      const dateB = getSafeDate(b.publishedAt);
      return dateB.getTime() - dateA.getTime();
    });
  }, [articles]);

  const latestArticle = sortedArticles[0];
  const previousArticles = sortedArticles.slice(1);

  return (
    <Card className="h-full flex flex-col min-h-[500px] max-h-[650px] shadow-sm border-l-4 border-l-primary overflow-hidden bg-white">
      <CardHeader className="flex-shrink-0 border-b bg-muted/5">
        <CardTitle className="flex items-center text-lg">
          <Rss className="mr-2 h-5 w-5 text-primary" />
          Frank&apos;s News Summary
        </CardTitle>
        <CardDescription className="text-xs">
          UK Market Intelligence generated by Frank Tadsworth-Bids.
        </CardDescription>
      </CardHeader>
      
      <CardContent className="flex-1 flex flex-col min-h-0 p-0 overflow-hidden">
        {isLoading ? (
          <div className="flex items-center justify-center flex-1">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
          </div>
        ) : !latestArticle ? (
            <div className="text-center text-muted-foreground p-8 text-sm flex-1 flex items-center justify-center">
              No news articles available at present.
            </div>
        ) : (
          <div className="flex-1 flex flex-col min-h-0 overflow-hidden">
            <div className="px-6 py-4 border-b bg-background flex-shrink-0">
              <h3 className="font-bold text-base leading-snug text-slate-900">{latestArticle.title}</h3>
              <div className="flex items-center gap-2 mt-2">
                <Clock className="h-3 w-3 text-primary" />
                <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-wider">
                  Published: {format(getSafeDate(latestArticle.publishedAt), 'd MMMM yyyy HH:mm')}
                </p>
                <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
              </div>
            </div>

            <div className="flex-1 min-h-0 relative bg-slate-50/20">
              <ScrollArea className="h-full w-full">
                <div className="p-6">
                  <p className="text-sm text-slate-600 whitespace-pre-wrap leading-relaxed">
                    {latestArticle.summary}
                  </p>
                </div>
              </ScrollArea>
            </div>
            
            <div className="px-6 py-3 border-t bg-muted/5 space-y-3 flex-shrink-0">
              <div className="flex items-center text-[10px] text-muted-foreground font-medium">
                 <span className="text-slate-400 mr-1.5 font-bold uppercase tracking-tighter">Source(s):</span>
                 <span className="italic truncate">{latestArticle.source}</span>
              </div>

              {!latestOnly && previousArticles.length > 0 && (
                <div className="space-y-2 pt-2 border-t">
                  <h4 className="text-[11px] font-bold uppercase tracking-tight text-slate-500">Previous Intel</h4>
                  <ScrollArea className="h-[120px] pr-4">
                    <Accordion type="single" collapsible className="w-full">
                      {previousArticles.map((article) => (
                        <AccordionItem value={article.id} key={article.id} className="border-none">
                            <AccordionTrigger className="text-[11px] font-semibold text-left hover:no-underline py-1.5 hover:text-primary transition-colors">
                               {article.title}
                            </AccordionTrigger>
                            <AccordionContent>
                               <div className="pb-3 px-1">
                                <p className="text-[11px] text-muted-foreground whitespace-pre-wrap leading-relaxed">{article.summary}</p>
                               </div>
                            </AccordionContent>
                        </AccordionItem>
                      ))}
                    </Accordion>
                  </ScrollArea>
                </div>
              )}

              {latestOnly && (
                  <Button variant="outline" size="sm" asChild className="w-full text-xs font-bold shadow-sm h-8 border-primary/20 hover:bg-primary/5">
                      <Link href="/dashboard/auction-academy">
                          View Full Intelligence Archive
                          <ArrowRight className="ml-2 h-3 w-3 text-primary" />
                      </Link>
                  </Button>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}